name: Feature request
about: Suggest an idea
title: "[FEATURE] "
labels: enhancement
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why does it matter?
